export const items = [
  {
    id: 1,
    name: "Glass",
    level: 1,
    parentItem: "0",
    parentId: null,
    parentClassName: null,
    quantity: 1,
    className: "glass",
    leadTime: 2,
    lotSize: 15,
    inStock: 30,
  },
  {
    id: 2,
    name: "Frame",
    level: 1,
    parentItem: "0",
    parentId: null,
    parentClassName: null,
    quantity: 1,
    className: "frame",
    leadTime: 2,
    lotSize: 25,
    inStock: 30,
  },
  {
    id: 3,
    name: "Screws",
    level: 1,
    parentItem: "0",
    parentId: null,
    parentClassName: null,
    quantity: 4,
    className: "screws",
    leadTime: 1,
    lotSize: 120,
    inStock: 80,
  },
  {
    id: 5,
    name: "Sealant",
    level: 1,
    parentItem: "0",
    parentId: null,
    quantity: 4,
    className: "sealant",
    parentClassName: null,
    leadTime: 1,
    lotSize: 60,
    inStock: 80,
  },
  {
    id: 6,
    name: "Wood",
    level: 2,
    parentItem: "Frame",
    parentId: 2,
    parentClassName: "frame",
    quantity: 4,
    className: "wood",
    leadTime: 1,
    lotSize: 100,
    inStock: 60,
  },
  {
    id: 7,
    name: "Metal brackets",
    level: 2,
    parentItem: "Frame",
    parentId: 4,
    parentClassName: "frame",
    quantity: 2,
    className: "metal_brackets",
    leadTime: 1,
    lotSize: 35,
    inStock: 25,
  },
];

export const categoriesData = [
  { name: "Całkowite zapotrzebowanie", className: "grossRequirements" },
  { name: "Planowane przyjęcia", className: "scheduledReceipts" },
  { name: "Przewidywane na stanie", className: "projectedAvailable" },
  { name: "Zapotrzebowanie netto", className: "netRequirements" },
  { name: "Planowane zamówienia", className: "plannedOrderReleases" },
  {
    name: "Planowane przyjęcie zamówień",
    className: "plannedOrderReceipts",
  },
];

export const productionParameters = [
  { name: "Czas realizacji", className: "leadTime" },
  { name: "Wielkość partii", className: "lotSize" },
  { name: "Ilość", className: "quantity" },
  { name: "Na stanie", className: "inStock" },
];
